// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcHmgr0z0twOTnjUfwp9FDcc6Y-NOhxtY',
    appId: '1:393009552498:web:f878db58229e22d2abf6eb',
    messagingSenderId: '393009552498',
    projectId: 'flutter-masterclass-28c6d',
    authDomain: 'flutter-masterclass-28c6d.firebaseapp.com',
    storageBucket: 'flutter-masterclass-28c6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-V3JSdKAUE92-sFBaJEhm2mURA9kR8TQ',
    appId: '1:393009552498:android:3af4e0bf37439121abf6eb',
    messagingSenderId: '393009552498',
    projectId: 'flutter-masterclass-28c6d',
    storageBucket: 'flutter-masterclass-28c6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABDCXvElVZYhMWTa4nt2I2LbRI5uDruC8',
    appId: '1:393009552498:ios:cfbc14504d6aba5babf6eb',
    messagingSenderId: '393009552498',
    projectId: 'flutter-masterclass-28c6d',
    storageBucket: 'flutter-masterclass-28c6d.appspot.com',
    iosBundleId: 'com.example.flutterRpg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABDCXvElVZYhMWTa4nt2I2LbRI5uDruC8',
    appId: '1:393009552498:ios:cfbc14504d6aba5babf6eb',
    messagingSenderId: '393009552498',
    projectId: 'flutter-masterclass-28c6d',
    storageBucket: 'flutter-masterclass-28c6d.appspot.com',
    iosBundleId: 'com.example.flutterRpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcHmgr0z0twOTnjUfwp9FDcc6Y-NOhxtY',
    appId: '1:393009552498:web:d0f35c6d4802277aabf6eb',
    messagingSenderId: '393009552498',
    projectId: 'flutter-masterclass-28c6d',
    authDomain: 'flutter-masterclass-28c6d.firebaseapp.com',
    storageBucket: 'flutter-masterclass-28c6d.appspot.com',
  );

}